export default function($scope) {
    $scope.editorOptions = {
        lineWrapping : true,
        lineNumbers: true,
        matchBrackets: true,
        mode: 'application/sparql-query'
    };
    $scope.queries = [
      {
        "created": "1455723755000",
        "name": "Find average for Moscow",
        "id": "1",
        "text": "REGISTER QUERY test AS PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> PREFIX ex: <http://example.com/#> PREFIX qudt: <http://qudt.org/schema/qudt#> PREFIX qudt-quantity: <http://qudt.org/vocab/quantity#> PREFIX ssncom: <http://purl.org/NET/ssnext/communication#> PREFIX ldo: <http://linkedgeodata.org/ontology/> PREFIX dul: <http://www.loa-cnr.it/ontologies/DUL.owl#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX geo:<http://www.w3.org/2003/01/geo/wgs84_pos#> PREFIX spatial:<http://jena.apache.org/spatial#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> CONSTRUCT { ?sensor a ex:Diff; ex:hasDiff ?diff; ex:hasAbsTemp ?value1;ex:hasAbsAvg ?absAvg;ex:hasAvg ?avg; ex:hasTime ?time1; ex:InGroup ?group. } FROM STREAM <http://ex.org/streams/test> [RANGE 40m STEP 20m] WHERE { {SERVICE <http://demo-1.semiot.ru:2323/ds/sparql> { SELECT ?lat ?long ?rad WHERE { \t?xza rdf:type ldo:City; \t\trdfs:label \"Moscow\"@en; \t\tgeo:long ?long; \t\tgeo:lat ?lat;\t\t<http://example.com#radius> ?rad.\t} } SERVICE <http://demo-1.semiot.ru:3030/ds/sparql> { SELECT ?sensor ?lat ?long ?rad WHERE { \t?loc spatial:nearby (?lat ?long ?rad 'km') . \t?xaz dul:hasLocation ?loc; \t\tssn:hasSubSystem ?sensor.\t}}{SELECT (AVG(?d) AS ?avg) (AVG(?v2) AS ?absAvg) WHERE { \t?o1 a ssn:Observation ; \t\tssn:observedBy ?sensor ; \t\tssn:observedProperty qudt-quantity:ThermodynamicTemperature ; \t\tssn:observationResultTime ?t1 ; \t\tssn:observationResult/ssn:hasValue/qudt:quantityValue ?v1. \t?o2 a ssn:Observation ; \t\tssn:observedBy ?sensor ; \t\tssn:observedProperty qudt-quantity:ThermodynamicTemperature ; \t\tssn:observationResultTime ?t2 ; \t\tssn:observationResult/ssn:hasValue/qudt:quantityValue ?v2 . \tFILTER(?o1!=?o2 && ?t1 > ?t2) \tBIND (?v1-?v2 AS ?d) } }} \t?obs1 a ssn:Observation ; \t\tssn:observedBy ?sensor ; \t\tssn:observedProperty qudt-quantity:ThermodynamicTemperature ; \t\tssn:observationResultTime ?time1 ; \t\tssn:observationResult/ssn:hasValue/qudt:quantityValue ?value1 .  \t?obs2 a ssn:Observation ; \t\tssn:observedBy ?sensor ;\t\tssn:observedProperty qudt-quantity:ThermodynamicTemperature ; \t\tssn:observationResultTime ?time2 ; \t\tssn:observationResult/ssn:hasValue/qudt:quantityValue ?value2 . \tFILTER(?obs1!=?obs2 && ?time1 > ?time2) \tFILTER(?value1 < ?absAvg+5 && ?value1 > ?absAvg -5)\tBIND (?value1-?value2 AS ?diff) \tBIND (if(?diff>?avg,1,2) AS ?group) }",
        "sparql": "PREFIX spatial:<http://jena.apache.org/spatial#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX geo:<http://www.w3.org/2003/01/geo/wgs84_pos#> PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> PREFIX dul: <http://www.loa-cnr.it/ontologies/DUL.owl#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX ldo: <http://linkedgeodata.org/ontology/> PREFIX ssncom: <http://purl.org/NET/ssnext/communication#> Select ?q WHERE{ \tSERVICE <http://demo-1.semiot.ru:2323/ds/sparql>{ \t\tSELECT ?long ?lat ?rad WHERE{ \t\t\t?xza rdf:type ldo:City; \t\t\t\trdfs:label \"Moscow\"@en; \t\t\t\tgeo:long ?long; \t\t\t\tgeo:lat ?lat;\t\t\t\t<http://example.com#radius> ?rad.\t\t} \t}\t?loc spatial:nearby (?lat ?long ?rad 'km') . \t?x dul:hasLocation ?loc; \t\tssncom:hasCommunicationEndpoint [ \t\t\tssncom:protocol \"WAMP\"; \t\t\tssncom:topic ?q \t\t]; }"
      },
      {
        "created": "1455723796000",
        "name": "Find average for Saint-Petersburg",
        "id": "2",
        "text": "REGISTER QUERY test AS PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> PREFIX ex: <http://example.com/#> PREFIX qudt: <http://qudt.org/schema/qudt#> PREFIX qudt-quantity: <http://qudt.org/vocab/quantity#> PREFIX ssncom: <http://purl.org/NET/ssnext/communication#> PREFIX ldo: <http://linkedgeodata.org/ontology/> PREFIX dul: <http://www.loa-cnr.it/ontologies/DUL.owl#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX geo:<http://www.w3.org/2003/01/geo/wgs84_pos#> PREFIX spatial:<http://jena.apache.org/spatial#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> CONSTRUCT { ?sensor a ex:Diff; ex:hasDiff ?diff; ex:hasAbsTemp ?value1;ex:hasAbsAvg ?absAvg;ex:hasAvg ?avg; ex:hasTime ?time1; ex:InGroup ?group. } FROM STREAM <http://ex.org/streams/test> [RANGE 40m STEP 20m] WHERE { {SERVICE <http://demo-1.semiot.ru:2323/ds/sparql> { SELECT ?lat ?long ?rad WHERE { \t?xza rdf:type ldo:City; \t\trdfs:label \"Saint-Petersburg\"@en; \t\tgeo:long ?long; \t\tgeo:lat ?lat;\t\t<http://example.com#radius> ?rad.\t} } SERVICE <http://demo-1.semiot.ru:3030/ds/sparql> { SELECT ?sensor ?lat ?long ?rad WHERE { \t?loc spatial:nearby (?lat ?long ?rad 'km') . \t?xaz dul:hasLocation ?loc; \t\tssn:hasSubSystem ?sensor.\t}}{SELECT (AVG(?d) AS ?avg) (AVG(?v2) AS ?absAvg) WHERE { \t?o1 a ssn:Observation ; \t\tssn:observedBy ?sensor ; \t\tssn:observedProperty qudt-quantity:ThermodynamicTemperature ; \t\tssn:observationResultTime ?t1 ; \t\tssn:observationResult/ssn:hasValue/qudt:quantityValue ?v1. \t?o2 a ssn:Observation ; \t\tssn:observedBy ?sensor ; \t\tssn:observedProperty qudt-quantity:ThermodynamicTemperature ; \t\tssn:observationResultTime ?t2 ; \t\tssn:observationResult/ssn:hasValue/qudt:quantityValue ?v2 . \tFILTER(?o1!=?o2 && ?t1 > ?t2) \tBIND (?v1-?v2 AS ?d) } }} \t?obs1 a ssn:Observation ; \t\tssn:observedBy ?sensor ; \t\tssn:observedProperty qudt-quantity:ThermodynamicTemperature ; \t\tssn:observationResultTime ?time1 ; \t\tssn:observationResult/ssn:hasValue/qudt:quantityValue ?value1 .  \t?obs2 a ssn:Observation ; \t\tssn:observedBy ?sensor ;\t\tssn:observedProperty qudt-quantity:ThermodynamicTemperature ; \t\tssn:observationResultTime ?time2 ; \t\tssn:observationResult/ssn:hasValue/qudt:quantityValue ?value2 . \tFILTER(?obs1!=?obs2 && ?time1 > ?time2) \tFILTER(?value1 < ?absAvg+5 && ?value1 > ?absAvg -5)\tBIND (?value1-?value2 AS ?diff) \tBIND (if(?diff>?avg,1,2) AS ?group) }",
        "sparql": "PREFIX spatial:<http://jena.apache.org/spatial#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX geo:<http://www.w3.org/2003/01/geo/wgs84_pos#> PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#> PREFIX dul: <http://www.loa-cnr.it/ontologies/DUL.owl#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX ldo: <http://linkedgeodata.org/ontology/> PREFIX ssncom: <http://purl.org/NET/ssnext/communication#> Select ?q WHERE{ \tSERVICE <http://demo-1.semiot.ru:2323/ds/sparql>{ \t\tSELECT ?long ?lat ?rad WHERE{ \t\t\t?xza rdf:type ldo:City; \t\t\t\trdfs:label \"Saint-Petersburg\"@en; \t\t\t\tgeo:long ?long; \t\t\t\tgeo:lat ?lat;\t\t\t\t<http://example.com#radius> ?rad.\t\t} \t}\t?loc spatial:nearby (?lat ?long ?rad 'km') . \t?x dul:hasLocation ?loc; \t\tssncom:hasCommunicationEndpoint [ \t\t\tssncom:protocol \"WAMP\"; \t\t\tssncom:topic ?q \t\t]; }"
      }
    ];
}