FROM ubuntu
RUN apt-get update
RUN apt-get install -y wget tar curl default-jdk ssh supervisor 
ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64/
ENV HBASE_HOME /opt/hbase/
ENV COMPRESSION "NONE"

#Download Hbase and extract
RUN cd /opt/ && wget http://archive.apache.org/dist/hbase/0.98.15/hbase-0.98.15-hadoop2-bin.tar.gz && \
tar xzvf hbase-0.98.15-hadoop2-bin.tar.gz && rm -rf hbase-0.98.15-hadoop2-bin.tar.gz && mv hbase-0.98.15-hadoop2 hbase

#Initialize sshd
RUN mkdir ~/.ssh && touch ~/.ssh/authorized_keys && ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
echo "Port 2122" >> /etc/ssh/ssh_config && perl -i -pe 's/Port 22/Port 2122/;' /etc/ssh/sshd_config && perl -i -pe 's/UsePAM yes/UsePAM no/;' /etc/ssh/sshd_config

#Set up HBase
RUN echo "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/" >> $HBASE_HOME/conf/hbase-env.sh
ADD hbase-site.xml $HBASE_HOME/conf/
ADD https://github.com/OpenTSDB/opentsdb/raw/master/src/create_table.sh /opt/create_table.sh

RUN echo "StrictHostKeyChecking no" > /root/.ssh/config && chmod 777 /opt/create_table.sh

#Set up supervisor
ADD run.sh /opt/
ADD hbase.conf /etc/supervisor/conf.d/hbase.conf

ADD backup.sh /opt/
ADD restore.sh /opt/
RUN mkdir $HBASE_HOME/logs && touch $HBASE_HOME/logs/log
WORKDIR /opt/

EXPOSE 60000
EXPOSE 60010
EXPOSE 60020
EXPOSE 60030
EXPOSE 2181
VOLUME $HBASE_HOME/logs/ /etc/hbase/

CMD ["supervisord", "-c", "/etc/supervisor/conf.d/hbase.conf"]
