FROM ubuntu:14.04
RUN apt-get update && apt-get install -y default-jdk tar automake build-essential python python-dev gnuplot curl
ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64/
RUN mkdir /opt/downloads/
ADD https://github.com/OpenTSDB/opentsdb/releases/download/v2.2.0/opentsdb-2.2.0.tar.gz /opt/downloads/
RUN tar xzvf /opt/downloads/opentsdb-2.2.0.tar.gz -C /opt/downloads/ && rm -rf /opt/downloads/opentsdb-2.2.0.tar.gz && mv /opt/downloads/opentsdb-2.2.0 /opt/opentsdb/
#RUN perl -i -pe 's/info/debug/;' /opt/opentsdb/src/logback.xml
RUN cd /opt/opentsdb/ && bash ./build.sh
RUN mkdir /opt/tmp/
ADD run.sh /opt/run.sh
EXPOSE 4242
VOLUME /opt/tmp/ /etc/opentsdb/
CMD ["sh", "/opt/run.sh"]
