FROM ubuntu
RUN apt-get update && apt-get install -y default-jdk tar ssh make curl git
ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64/
RUN mkdir /opt/downloads/
ADD https://github.com/OpenTSDB/opentsdb/releases/download/2.1.1/opentsdb-2.1.1.tar.gz /opt/downloads/
#RUN tar xzvf /opt/downloads/opentsdb-2.1.1.tar.gz -C /opt/downloads/ && rm -rf /opt/downloads/opentsdb-2.1.1.tar.gz && mv /opt/downloads/opentsdb-2.1.1 /opt/opentsdb/
RUN git clone -b next --single-branch git://github.com/OpenTSDB/opentsdb.git /opt/opentsdb
#RUN perl -i -pe 's/info/debug/;' /opt/opentsdb/src/logback.xml
RUN cd /opt/opentsdb/ && bash ./build.sh
RUN mkdir /opt/tmp/
ADD run.sh /opt/run.sh
EXPOSE 4242
VOLUME /opt/tmp/
CMD ["sh", "/opt/run.sh"]
