PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX ssncom: <http://purl.org/NET/ssnext/communication#>

SELECT ?system ?coap ?wamp {
    ?system a ssn:System ;
        ssn:hasSubsystem ?sensor .
    ?sensor a ssn:Sensor ;
        ssncom:hasCommunicationEndpoint ?coap ;
        ssncom:hasCommunicationEndpoint ?wamp .
    ?coap ssncom:protocol "COAP" .
    ?wamp ssncom:protocol "WAMP" .
}
