FROM ubuntu:14.04

RUN apt-get update && apt-get install -y mysql-server
RUN service mysql start && mysql --execute="create database semiot; connect semiot;\
 create table credentials (id int (4), login char(40), password char(20), role char(10), primary key(id));\
 insert into credentials values ('1', 'root', 'root', 'admin');\
 grant all privileges on semiot.* to root@'%';"


CMD ["mysqld", "--bind-address=0.0.0.0"]
